config/routes.rb
Greenlist::Application.routes.draw do
  resources :items

  root to: 'items#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  def self.RED; 0; end
  def self.YELLOW; 1; end
  def self.GREEN; 2; end

  attr_accessible :name, :status
  scope :red, where(status: Item.RED)
  scope :yellow, where(status: Item.YELLOW)
  scope :green, where(status: Item.GREEN)

  before_create :set_initial_status 

  def update_status!
    self.status = (status - 1) % 3
    save!
  end

  def set_initial_status
    self.status = Item.RED
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @red_items = Item.red
    @yellow_items = Item.yellow
    @green_items = Item.green
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create!(params[:item])
    respond_to do |format|
      format.html { redirect_to items_path }
      format.js
    end
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update_status!
    respond_to do |format|
      format.html { redirect_to items_path }
      format.js
    end
  end

  def destroy
    @item = Item.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to items_path }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, remote: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit 'Add' %>
<% end %>

app/views/items/_item.html.erb
<%= form_for item, remote: true do |f| %>
  <%= f.submit 'Update' %>
  <%= f.label item.name %>
  <%= link_to("&times;".html_safe, item, method: :delete, data: {confirm: 'Are you sure?'}, remote: true) %>
<% end %>

app/views/items/create.js.erb
$("#new_item").remove();
$("#new_link").show();
$("#red_items").append("<%= j render(@item) %>");
$('#edit_item_<%= @item.id %>').submitOnClick();

app/views/items/destroy.js.erb
$("#edit_item_<%= @item.id %>").remove();

app/views/items/index.html.erb
<h1>Greenlist</h1>
<div class="items", id="red_items">
  <%= render @red_items %>
</div>
<div class="items", id="yellow_items">
  <%= render @yellow_items %>
</div>
<div class="items", id="green_items">
  <%= render @green_items %>
</div>
<%= link_to "Add Item", new_item_path, id: 'new_link', remote: true %>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= render 'form' %>
<p><%= link_to "Back to Items", items_path %>

app/views/items/new.js.erb
$('#new_link').hide().after("<%= j render("form") %>")

app/views/items/update.js.erb
<% case @item.status %>
<% when Item.RED %>
  $('#edit_item_<%= @item.id %>').appendTo('#red_items');
<% when Item.YELLOW %>
  $('#edit_item_<%= @item.id %>').appendTo('#yellow_items');
<% when Item.GREEN %>
  $('#edit_item_<%= @item.id %>').appendTo('#green_items');
<% else %>
  alert('unknown item status');
  $('#edit_item_<%= @item.id %>').appendTo('#red_items');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greenlist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>